# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_control = QtWidgets.QWidget(self.centralwidget)
        self.widget_control.setObjectName("widget_control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_control)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_control_1 = QtWidgets.QWidget(self.widget_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_control_1.sizePolicy().hasHeightForWidth())
        self.widget_control_1.setSizePolicy(sizePolicy)
        self.widget_control_1.setObjectName("widget_control_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_control_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_base_frame_id = QtWidgets.QWidget(self.widget_control_1)
        self.widget_base_frame_id.setObjectName("widget_base_frame_id")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_base_frame_id)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_base_frame_id = QtWidgets.QLabel(self.widget_base_frame_id)
        self.label_base_frame_id.setObjectName("label_base_frame_id")
        self.horizontalLayout_7.addWidget(self.label_base_frame_id)
        self.lineEdit_base_frame_id = QtWidgets.QLineEdit(self.widget_base_frame_id)
        self.lineEdit_base_frame_id.setObjectName("lineEdit_base_frame_id")
        self.horizontalLayout_7.addWidget(self.lineEdit_base_frame_id)
        self.verticalLayout_2.addWidget(self.widget_base_frame_id)
        self.widget_child_frame_id = QtWidgets.QWidget(self.widget_control_1)
        self.widget_child_frame_id.setObjectName("widget_child_frame_id")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_child_frame_id)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_child_frame_id = QtWidgets.QLabel(self.widget_child_frame_id)
        self.label_child_frame_id.setObjectName("label_child_frame_id")
        self.horizontalLayout_8.addWidget(self.label_child_frame_id)
        self.lineEdit_child_frame_id = QtWidgets.QLineEdit(self.widget_child_frame_id)
        self.lineEdit_child_frame_id.setObjectName("lineEdit_child_frame_id")
        self.horizontalLayout_8.addWidget(self.lineEdit_child_frame_id)
        self.verticalLayout_2.addWidget(self.widget_child_frame_id)
        self.pushButton_publish = QtWidgets.QPushButton(self.widget_control_1)
        self.pushButton_publish.setObjectName("pushButton_publish")
        self.verticalLayout_2.addWidget(self.pushButton_publish)
        self.verticalLayout_3.addWidget(self.widget_control_1)
        self.line = QtWidgets.QFrame(self.widget_control)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.widget_control_2 = QtWidgets.QWidget(self.widget_control)
        self.widget_control_2.setObjectName("widget_control_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_control_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.widget_control_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_info = QtWidgets.QLabel(self.widget)
        self.label_info.setObjectName("label_info")
        self.verticalLayout_6.addWidget(self.label_info)
        self.widget_x = QtWidgets.QWidget(self.widget)
        self.widget_x.setObjectName("widget_x")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_x)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_x = QtWidgets.QLabel(self.widget_x)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout.addWidget(self.label_x)
        self.horizontalSlider_x = QtWidgets.QSlider(self.widget_x)
        self.horizontalSlider_x.setMaximum(1000)
        self.horizontalSlider_x.setProperty("value", 500)
        self.horizontalSlider_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_x.setObjectName("horizontalSlider_x")
        self.horizontalLayout.addWidget(self.horizontalSlider_x)
        self.doubleSpinBox_x = QtWidgets.QDoubleSpinBox(self.widget_x)
        self.doubleSpinBox_x.setMinimum(-5.0)
        self.doubleSpinBox_x.setMaximum(5.0)
        self.doubleSpinBox_x.setSingleStep(0.01)
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.horizontalLayout.addWidget(self.doubleSpinBox_x)
        self.pushButton_reset_x = QtWidgets.QPushButton(self.widget_x)
        self.pushButton_reset_x.setObjectName("pushButton_reset_x")
        self.horizontalLayout.addWidget(self.pushButton_reset_x)
        self.verticalLayout_6.addWidget(self.widget_x)
        self.widget_y = QtWidgets.QWidget(self.widget)
        self.widget_y.setObjectName("widget_y")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_y)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_y = QtWidgets.QLabel(self.widget_y)
        self.label_y.setObjectName("label_y")
        self.horizontalLayout_2.addWidget(self.label_y)
        self.horizontalSlider_y = QtWidgets.QSlider(self.widget_y)
        self.horizontalSlider_y.setMaximum(1000)
        self.horizontalSlider_y.setProperty("value", 500)
        self.horizontalSlider_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_y.setObjectName("horizontalSlider_y")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_y)
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.widget_y)
        self.doubleSpinBox_y.setMinimum(-5.0)
        self.doubleSpinBox_y.setMaximum(5.0)
        self.doubleSpinBox_y.setSingleStep(0.01)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_y)
        self.pushButton_reset_y = QtWidgets.QPushButton(self.widget_y)
        self.pushButton_reset_y.setObjectName("pushButton_reset_y")
        self.horizontalLayout_2.addWidget(self.pushButton_reset_y)
        self.verticalLayout_6.addWidget(self.widget_y)
        self.widget_z = QtWidgets.QWidget(self.widget)
        self.widget_z.setObjectName("widget_z")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_z)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_z = QtWidgets.QLabel(self.widget_z)
        self.label_z.setObjectName("label_z")
        self.horizontalLayout_3.addWidget(self.label_z)
        self.horizontalSlider_z = QtWidgets.QSlider(self.widget_z)
        self.horizontalSlider_z.setMaximum(1000)
        self.horizontalSlider_z.setProperty("value", 500)
        self.horizontalSlider_z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_z.setObjectName("horizontalSlider_z")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_z)
        self.doubleSpinBox_z = QtWidgets.QDoubleSpinBox(self.widget_z)
        self.doubleSpinBox_z.setMinimum(-5.0)
        self.doubleSpinBox_z.setMaximum(5.0)
        self.doubleSpinBox_z.setSingleStep(0.01)
        self.doubleSpinBox_z.setObjectName("doubleSpinBox_z")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_z)
        self.pushButton_reset_z = QtWidgets.QPushButton(self.widget_z)
        self.pushButton_reset_z.setObjectName("pushButton_reset_z")
        self.horizontalLayout_3.addWidget(self.pushButton_reset_z)
        self.verticalLayout_6.addWidget(self.widget_z)
        self.widget_roll = QtWidgets.QWidget(self.widget)
        self.widget_roll.setObjectName("widget_roll")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_roll)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_roll = QtWidgets.QLabel(self.widget_roll)
        self.label_roll.setObjectName("label_roll")
        self.horizontalLayout_4.addWidget(self.label_roll)
        self.horizontalSlider_roll = QtWidgets.QSlider(self.widget_roll)
        self.horizontalSlider_roll.setMaximum(360)
        self.horizontalSlider_roll.setProperty("value", 180)
        self.horizontalSlider_roll.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_roll.setObjectName("horizontalSlider_roll")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_roll)
        self.spinBox_roll = QtWidgets.QSpinBox(self.widget_roll)
        self.spinBox_roll.setMinimum(-180)
        self.spinBox_roll.setMaximum(180)
        self.spinBox_roll.setObjectName("spinBox_roll")
        self.horizontalLayout_4.addWidget(self.spinBox_roll)
        self.pushButton_reset_roll = QtWidgets.QPushButton(self.widget_roll)
        self.pushButton_reset_roll.setObjectName("pushButton_reset_roll")
        self.horizontalLayout_4.addWidget(self.pushButton_reset_roll)
        self.verticalLayout_6.addWidget(self.widget_roll)
        self.widget_pitch = QtWidgets.QWidget(self.widget)
        self.widget_pitch.setObjectName("widget_pitch")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_pitch)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_pitch = QtWidgets.QLabel(self.widget_pitch)
        self.label_pitch.setObjectName("label_pitch")
        self.horizontalLayout_5.addWidget(self.label_pitch)
        self.horizontalSlider_pitch = QtWidgets.QSlider(self.widget_pitch)
        self.horizontalSlider_pitch.setMaximum(360)
        self.horizontalSlider_pitch.setProperty("value", 180)
        self.horizontalSlider_pitch.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pitch.setObjectName("horizontalSlider_pitch")
        self.horizontalLayout_5.addWidget(self.horizontalSlider_pitch)
        self.spinBox_pitch = QtWidgets.QSpinBox(self.widget_pitch)
        self.spinBox_pitch.setMinimum(-180)
        self.spinBox_pitch.setMaximum(180)
        self.spinBox_pitch.setObjectName("spinBox_pitch")
        self.horizontalLayout_5.addWidget(self.spinBox_pitch)
        self.pushButton_reset_pitch = QtWidgets.QPushButton(self.widget_pitch)
        self.pushButton_reset_pitch.setObjectName("pushButton_reset_pitch")
        self.horizontalLayout_5.addWidget(self.pushButton_reset_pitch)
        self.verticalLayout_6.addWidget(self.widget_pitch)
        self.widget_yaw = QtWidgets.QWidget(self.widget)
        self.widget_yaw.setObjectName("widget_yaw")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_yaw)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_yaw = QtWidgets.QLabel(self.widget_yaw)
        self.label_yaw.setObjectName("label_yaw")
        self.horizontalLayout_6.addWidget(self.label_yaw)
        self.horizontalSlider_yaw = QtWidgets.QSlider(self.widget_yaw)
        self.horizontalSlider_yaw.setMaximum(360)
        self.horizontalSlider_yaw.setProperty("value", 180)
        self.horizontalSlider_yaw.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_yaw.setObjectName("horizontalSlider_yaw")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_yaw)
        self.spinBox_yaw = QtWidgets.QSpinBox(self.widget_yaw)
        self.spinBox_yaw.setMinimum(-180)
        self.spinBox_yaw.setMaximum(180)
        self.spinBox_yaw.setObjectName("spinBox_yaw")
        self.horizontalLayout_6.addWidget(self.spinBox_yaw)
        self.pushButton_reset_yaw = QtWidgets.QPushButton(self.widget_yaw)
        self.pushButton_reset_yaw.setObjectName("pushButton_reset_yaw")
        self.horizontalLayout_6.addWidget(self.pushButton_reset_yaw)
        self.verticalLayout_6.addWidget(self.widget_yaw)
        self.pushButton_reset_all = QtWidgets.QPushButton(self.widget)
        self.pushButton_reset_all.setObjectName("pushButton_reset_all")
        self.verticalLayout_6.addWidget(self.pushButton_reset_all)
        self.verticalLayout.addWidget(self.widget)
        self.widget_buttons = QtWidgets.QWidget(self.widget_control_2)
        self.widget_buttons.setObjectName("widget_buttons")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_buttons)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_load = QtWidgets.QPushButton(self.widget_buttons)
        self.pushButton_load.setObjectName("pushButton_load")
        self.verticalLayout_5.addWidget(self.pushButton_load)
        self.pushButton_save = QtWidgets.QPushButton(self.widget_buttons)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_5.addWidget(self.pushButton_save)
        self.pushButton_delete = QtWidgets.QPushButton(self.widget_buttons)
        self.pushButton_delete.setAutoFillBackground(False)
        self.pushButton_delete.setStyleSheet("background-color: rgb(239, 41, 41)")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.verticalLayout_5.addWidget(self.pushButton_delete)
        self.verticalLayout.addWidget(self.widget_buttons)
        self.verticalLayout_3.addWidget(self.widget_control_2)
        self.horizontalLayout_9.addWidget(self.widget_control)
        self.widget_info = QtWidgets.QWidget(self.centralwidget)
        self.widget_info.setObjectName("widget_info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_info)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_info)
        self.tableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(194)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.textBrowser_info = QtWidgets.QTextBrowser(self.widget_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_info.sizePolicy().hasHeightForWidth())
        self.textBrowser_info.setSizePolicy(sizePolicy)
        self.textBrowser_info.setObjectName("textBrowser_info")
        self.verticalLayout_4.addWidget(self.textBrowser_info)
        self.horizontalLayout_9.addWidget(self.widget_info)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_base_frame_id.setText(_translate("MainWindow", "base_frame_id"))
        self.label_child_frame_id.setText(_translate("MainWindow", "child_frame_id"))
        self.pushButton_publish.setText(_translate("MainWindow", "Publish"))
        self.label_info.setText(_translate("MainWindow", "Nothing selected"))
        self.label_x.setText(_translate("MainWindow", "x"))
        self.pushButton_reset_x.setText(_translate("MainWindow", "Reset"))
        self.label_y.setText(_translate("MainWindow", "y"))
        self.pushButton_reset_y.setText(_translate("MainWindow", "Reset"))
        self.label_z.setText(_translate("MainWindow", "z"))
        self.pushButton_reset_z.setText(_translate("MainWindow", "Reset"))
        self.label_roll.setText(_translate("MainWindow", "r"))
        self.pushButton_reset_roll.setText(_translate("MainWindow", "Reset"))
        self.label_pitch.setText(_translate("MainWindow", "p"))
        self.pushButton_reset_pitch.setText(_translate("MainWindow", "Reset"))
        self.label_yaw.setText(_translate("MainWindow", "y"))
        self.pushButton_reset_yaw.setText(_translate("MainWindow", "Reset"))
        self.pushButton_reset_all.setText(_translate("MainWindow", "Reset All"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
        self.textBrowser_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nothing selected</p></body></html>"))
